version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - postgres
    entrypoint: ["python", "app.py","runserver"]

  postgres:
    restart: unless-stopped
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}

  pgadmin4:
    restart: unless-stopped
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"

volumes: 
  flask_postgres:

networks:
      default:
        external:
          name: postgres-network